### ISSUE TITLE
Empty response, no error messages anywhere

### ISSUE THREAD

**Issue by mav808** [mvanduijker/viewtube-all-in-one#1]
Startup log doesn't have any errors, but only an empty response is returned when you hit the port.

**Comment by mvanduijker** [comment]
Could you give some more info? How do you start the container?

**Comment by mav808** [comment]
Thanks for replying. I'm running this on a Synology NAS and the only thing I've changed to the default startup is to map the /data folder. I can see that config.json is created there along with 'db' and 'redis' folders. When I run curl when the container is running I get this...

`mav@lmac ~ % curl http://192.168.1.44:8066`
`curl: (52) Empty reply from server`

When the container isn't running I get "couldn't connect" rather than empty reply so something is up, just not returning anything.

Here is the log in case that is helpful...
[viewtube.csv](https://github.com/mvanduijker/viewtube-all-in-one/files/14165981/viewtube.csv)

Is there anything I can try to help debug this?

Much thanks.

**Comment by mvanduijker** [comment]
Does your Synology NAS support linux/amd64 images?

**Comment by mav808** [comment]
Yes, it's a 918+, which has an Intel Celeron. The container starts, and I can connect to it and start a shell. I can run ps (after using apt to install it) and can see that redis and "node /home/app/server/dist/main.cjs" are running.

**Comment by mvanduijker** [comment]
For me it works...

Could you try the following?

* double check the permissions of your volume (or try run it without a volume?)
* try the dev tag instead of latest
* Can you give the output with:

```
curl -v http://192.168.1.44:8066
```

**Comment by Lippiece** [comment]
```
╰─ curl -v 0.0.0.0:36357
*   Trying 0.0.0.0:36357...
* Connected to 0.0.0.0 (0.0.0.0) port 36357
> GET / HTTP/1.1
> Host: 0.0.0.0:36357
> User-Agent: curl/8.6.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection
curl: (56) Recv failure: Connection reset by peer
╰─ curl -v 0.0.0.0:36357
*   Trying 0.0.0.0:36357...
* Connected to 0.0.0.0 (0.0.0.0) port 36357
> GET / HTTP/1.1
> Host: 0.0.0.0:36357
> User-Agent: curl/8.6.0
> Accept: */*
> 
* Empty reply from server
* Closing connection
curl: (52) Empty reply from server
```

**Comment by Lippiece** [comment]
This is apparently a MongoDB issue with AVX. I'm running this on an old machine which doesn't support the AVX instructions.

**Comment by mvanduijker** [comment]
Hmmm interesting https://www.mongodb.com/docs/manual/administration/production-notes/#x86_64 it seems just to be a requirement of mongodb. Not much I can do about it. Would probably have the same issue if you would run mongodb separately.

**Comment by mvanduijker** [comment]
Documented in the readme.
